# Project language
language: php
php:
    - 7.1

# Allows use container-based infrastructure
sudo: false

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Define an environment variable
env:
  - SYMFONY_VERSION="3.3.*" DB=sqlite

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - cd oagtoolbox
  - composer install
  - cp app/config/parameters.yml.sqlite app/config/parameters.yml
    # - php bin/console doctrine:database:create --env=test
    # - php bin/console doctrine:schema:create --env=test

# Run script
script:
  - ./vendor/bin/simple-phpunit -c phpunit.xml

# After a build, send email notification with the build results
notifications:
  email: tobias@neontribe.co.uk
