parameters:
    oag:
        cove:
            uri: http://localhost:8008
        geocoder:
            uri: http://localhost:8009
        autogeocoder:
            uri: http://localhost:8010
        dportal:
            uri: http://localhost:8011
        classifier:
            uri: http://gis.foundationcenter.org/OpenAgCoder/extract_codes.php
    oagfiles_directory: '%kernel.project_dir%/web/uploads/oagfiles'
    oagxml_directory: '%kernel.project_dir%/web/xml/oagfiles'