services:
    OagBundle\:
        # This could be just ../.. but I have included the bundle name for readability
        resource: '../../../OagBundle/*'
        public: true
        exclude: '../../../OagBundle/{Entity,Repository,Tests,Interfaces}'
        calls:
            - [setContainer, ['@service_container']]


    oag.twig_extension:
        class: OagBundle\Twig\OagExtension
        tags:
            - { name: twig.extension }